In [13]:
# 1.VARIABLE

print("1.VARIABLES")
pi = 22 / 7
print(type(pi))  

for_= 4  # for=4 will  raise a SyntaxError
print(for_)

P = 1000  
R = 5     
T = 3     
Simple_Interest = P * R * T / 100
print(Simple_Interest)  
import math
print("______________________________________________________________________________________________________________________________________________")

#2.NUMBERS

print("2.NUMBERS")
def formatstring(number, character):
    return "The number is {} and the character is '{}'".format(number, character)
result = formatstring(145, 'o')
print(result)  

radius = 84
pi = 3.14
Area = pi * radius ** 2
print(Area)  

water_per_sqm = 1.4
total_water = Area * water_per_sqm
print(int(total_water))  

distance = 490
Time_in_Minutes = 7
Time_in_Seconds = Time_in_Minutes * 60
speed = distance / Time_in_Seconds
print(int(speed))
print("______________________________________________________________________________________________________________________________________________")

#3.LIST OPERATION

print("3.LIST")
justice_league = ["Superman", "Batman", "Wonder Woman", "Flash", "Aquaman", "Green Lantern"]
print(len(justice_league))  

justice_league.append("Batgirl")
justice_league.append("Nightwing")
print(justice_league)  

justice_league.remove("Wonder Woman")
justice_league.insert(0, "Wonder Woman")
print(justice_league)

index_aquaman = justice_league.index("Aquaman")
index_flash = justice_league.index("Flash")

justice_league.remove("Green Lantern")
justice_league.insert(index_flash, "Green Lantern")
print(justice_league)  

new_members = ["Cyborg", "Shazam", "Hawkgirl", "Martian Manhunter", "Green Arrow"]
justice_league = new_members
print(justice_league)  

justice_league.sort()
new_leader = justice_league[0]
print(justice_league)
print("New leader:", new_leader)
print("______________________________________________________________________________________________________________________________________________")

4.#IF CODITION


print("4.IF CONDITION")
height = float(input("Enter height in meters: "))
weight = float(input("Enter weight in kilograms: "))
BMI = weight / (height ** 2)
if BMI >= 30:
    print("Obesity")
elif 25 <= BMI < 30:
    print("Overweight")
elif 18.5 <= BMI < 25:
    print("Normal")
else:
    print("Underweight")


Australia = ["Sydney", "Melbourne", "Brisbane", "Perth"]
Uae = ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"]
India = ["Mumbai", "Bangalore", "Chennai", "Delhi"]
city = input("Enter a city name: ")
if city in Australia:
    print(f"{city} is in Australia")
elif city in Uae:
    print(f"{city} is in UAE")
elif city in India:
    print(f"{city} is in India")
else:
    print("City not found")


city1 = input("Enter the first city: ")
city2 = input("Enter the second city: ")
if city1 in Australia and city2 in Australia:
    print("Both cities are in Australia")
elif city1 in Uae and city2 in Uae:
    print("Both cities are in UAE")
elif city1 in India and city2 in India:
    print("Both cities are in India")
else:
    print("They don't belong to the same country")
print("______________________________________________________________________________________________________________________________________________")

#5.DICTIONARY

print("5.DICTIONARY")
friends = ["Deepika", "Harini", "Srimathi", "Haripriya", "Nithiya"]
friends_tuples = [(name, len(name)) for name in friends]
print(friends_tuples)  

your_expenses = {
    "Hotel": 1200,
    "Food": 800,
    "Transportation": 500,
    "Attractions": 300,
    "Miscellaneous": 200
}

partner_expenses = {
    "Hotel": 1000,
    "Food": 900,
    "Transportation": 600,
    "Attractions": 400,
    "Miscellaneous": 150
}

total_your_expenses = sum(your_expenses.values())
total_partner_expenses = sum(partner_expenses.values())

print(f"Your total expenses: {total_your_expenses}")
print(f"Partner's total expenses: {total_partner_expenses}")

if total_your_expenses > total_partner_expenses:
    print("You spent more money overall.")
else:
    print("Your partner spent more money overall.")


diff_category = max(your_expenses, key=lambda k: abs(your_expenses[k] - partner_expenses[k]))
diff_amount = abs(your_expenses[diff_category] - partner_expenses[diff_category])

print(f"Category with significant difference: {diff_category}")
print(f"Difference amount: {diff_amount}")
print("____________________________________________________________________________________________________________________________________________")

1.VARIABLES
<class 'float'>
4
150.0
______________________________________________________________________________________________________________________________________________
2.NUMBERS
The number is 145 and the character is 'o'
22155.84
31018
1
______________________________________________________________________________________________________________________________________________
3.LIST
6
['Superman', 'Batman', 'Wonder Woman', 'Flash', 'Aquaman', 'Green Lantern', 'Batgirl', 'Nightwing']
['Wonder Woman', 'Superman', 'Batman', 'Flash', 'Aquaman', 'Green Lantern', 'Batgirl', 'Nightwing']
['Wonder Woman', 'Superman', 'Batman', 'Green Lantern', 'Flash', 'Aquaman', 'Batgirl', 'Nightwing']
['Cyborg', 'Shazam', 'Hawkgirl', 'Martian Manhunter', 'Green Arrow']
['Cyborg', 'Green Arrow', 'Hawkgirl', 'Martian Manhunter', 'Shazam']
New leader: Cyborg
______________________________________________________________________________________________________________________________________________
4.IF CONDITION

Enter height in meters:  1.57
Enter weight in kilograms:  59

Normal

Enter a city name:  Mumbai

Mumbai is in India

Enter the first city:  Chennai
Enter the second city:  Perth

They don't belong to the same country
______________________________________________________________________________________________________________________________________________
5.DICTIONARY
[('Deepika', 7), ('Harini', 6), ('Srimathi', 8), ('Haripriya', 9), ('Nithiya', 7)]
Your total expenses: 3000
Partner's total expenses: 3050
Your partner spent more money overall.
Category with significant difference: Hotel
Difference amount: 200
____________________________________________________________________________________________________________________________________________